export const nationNameMap: Record<string, string> = {
  Indonesia: "Indonesia",
  Malaysia: "Malaysia",
  Chile: "Chile",
  Bolivia: "Bolivia",
  Peru: "Perú",
  Argentina: "Argentina",
  "Dhekelia Sovereign Base Area": "Dhekelia",
  Cyprus: "Κύπρος",
  India: "India",
  China: "中国",
  Israel: "ישראל",
  Palestine: "فلسطين",
  Lebanon: "لبنان",
  Ethiopia: "ኢትዮጵያ",
  "South Sudan": "South Sudan",
  Somalia: "Soomaaliya",
  Kenya: "Kenya",
  Malawi: "Malawi",
  "United Republic of Tanzania": "Tanzania",
  Syria: "سوريا",
  Somaliland: "Somaliland",
  France: "France",
  Suriname: "Suriname",
  Guyana: "Guyana",
  "South Korea": "대한민국",
  "North Korea": "조선민주주의인민공화국",
  Morocco: "المغرب",
  "Western Sahara": "الصحراء الغربية",
  "Costa Rica": "Costa Rica",
  Nicaragua: "Nicaragua",
  "Republic of the Congo": "Congo",
  "Democratic Republic of the Congo": "Congo-Kinshasa",
  Bhutan: "འབྲུག",
  Ukraine: "Україна",
  Belarus: "Беларусь",
  Namibia: "Namibia",
  "South Africa": "South Africa",
  Oman: "عُمان",
  Uzbekistan: "Oʻzbekiston",
  Kazakhstan: "Қазақстан",
  Tajikistan: "Тоҷикистон",
  Lithuania: "Lietuva",
  Brazil: "Brasil",
  Uruguay: "Uruguay",
  Mongolia: "Монгол",
  Russia: "Россия",
  Czechia: "Česko",
  Germany: "Deutschland",
  Estonia: "Eesti",
  Latvia: "Latvija",
  Norway: "Norge",
  Sweden: "Sverige",
  Finland: "Suomi",
  Vietnam: "Việt Nam",
  Cambodia: "កម្ពុជា",
  Luxembourg: "Lëtzebuerg",
  "United Arab Emirates": "الإمارات",
  Belgium: "België",
  Georgia: "საქართველო",
  "North Macedonia": "Северна Македонија",
  Albania: "Shqipëria",
  Azerbaijan: "Azərbaycan",
  Kosovo: "Kosovë",
  Turkey: "Türkiye",
  Spain: "España",
  Laos: "ລາວ",
  Kyrgyzstan: "Кыргызстан",
  Armenia: "Հայաստան",
  Denmark: "Danmark",
  Libya: "ليبيا",
  Tunisia: "تونس",
  Romania: "România",
  Hungary: "Magyarország",
  Slovakia: "Slovensko",
  Poland: "Polska",
  Ireland: "Éire",
  "United Kingdom": "United Kingdom",
  Greece: "Ελλάδα",
  Zambia: "Zambia",
  "Sierra Leone": "Sierra Leone",
  Guinea: "Guinée",
  Liberia: "Liberia",
  "Central African Republic": "République centrafricaine",
  Sudan: "السودان",
  Djibouti: "Djibouti",
  Eritrea: "ኤርትራ",
  Austria: "Österreich",
  Iraq: "العراق",
  Italy: "Italia",
  Switzerland: "Schweiz",
  Iran: "ایران",
  Netherlands: "Nederland",
  Liechtenstein: "Liechtenstein",
  "Ivory Coast": "Côte d’Ivoire",
  "Republic of Serbia": "Srbija",
  Mali: "Mali",
  Senegal: "Sénégal",
  Nigeria: "Nigeria",
  Benin: "Bénin",
  Angola: "Angola",
  Croatia: "Hrvatska",
  Slovenia: "Slovenija",
  Qatar: "قطر",
  "Saudi Arabia": "السعودية",
  Botswana: "Botswana",
  Zimbabwe: "Zimbabwe",
  Pakistan: "پاکستان",
  Bulgaria: "България",
  Thailand: "ประเทศไทย",
  "San Marino": "San Marino",
  Haiti: "Haïti",
  "Dominican Republic": "República Dominicana",
  Chad: "Tchad",
  Kuwait: "الكويت",
  "El Salvador": "El Salvador",
  Guatemala: "Guatemala",
  "East Timor": "Timor-Leste",
  Brunei: "Brunei",
  Monaco: "Monaco",
  Algeria: "الجزائر",
  Mozambique: "Moçambique",
  eSwatini: "eSwatini",
  Burundi: "Burundi",
  Rwanda: "Rwanda",
  Myanmar: "မြန်မာ",
  Bangladesh: "বাংলাদেশ",
  Andorra: "Andorra",
  Afghanistan: "افغانستان",
  Montenegro: "Crna Gora",
  "Bosnia and Herzegovina": "Bosna i Hercegovina",
  Uganda: "Uganda",
  Cuba: "Cuba",
  Honduras: "Honduras",
  Ecuador: "Ecuador",
  Colombia: "Colombia",
  Paraguay: "Paraguay",
  Portugal: "Portugal",
  Moldova: "Moldova",
  Turkmenistan: "Türkmenistan",
  Jordan: "الأردن",
  Nepal: "नेपाल",
  Lesotho: "Lesotho",
  Cameroon: "Cameroun",
  Gabon: "Gabon",
  Niger: "Niger",
  "Burkina Faso": "Burkina Faso",
  Togo: "Togo",
  Ghana: "Ghana",
  "Guinea-Bissau": "Guiné-Bissau",
  Gibraltar: "Gibraltar",
  "United States of America": "United States",
  Canada: "Canada",
  Mexico: "México",
  Belize: "Belize",
  Panama: "Panamá",
  Venezuela: "Venezuela",
  "Papua New Guinea": "Papua New Guinea",
  Egypt: "مصر",
  Yemen: "اليمن",
  Mauritania: "موريتانيا",
  "Equatorial Guinea": "Guinea Ecuatorial",
  Gambia: "Gambia",
  "Hong Kong S.A.R.": "香港",
  Vatican: "Città del Vaticano",
  Antarctica: "Antarctica",
  Australia: "Australia",
  Greenland: "Kalaallit Nunaat",
  Fiji: "Fiji",
  "New Zealand": "New Zealand",
  Madagascar: "Madagasikara",
  Philippines: "Philippines",
  "Sri Lanka": "ශ්‍රී ලංකාව",
  Japan: "日本",
  Iceland: "Ísland",
  Malta: "Malta",
  Singapore: "Singapore",
  Tonga: "Tonga",
  Samoa: "Samoa",
  "Solomon Islands": "Solomon Islands",
  Maldives: "Maldives",
  Nauru: "Nauru",
  Vanuatu: "Vanuatu",
  Palau: "Palau",
  Bahrain: "البحرين",
  "Siachen Glacier": "Siachen Glacier",
  "Baykonur Cosmodrome": "Baikonur Cosmodrome",
  "Akrotiri Sovereign Base Area": "Akrotiri",
  "Southern Patagonian Ice Field": "Southern Patagonian Ice Field",
  "Bir Tawil": "Bir Tawil",
  "New Caledonia": "New Caledonia",
  Curaçao: "Curaçao",
  Aruba: "Aruba",
  "The Bahamas": "Bahamas",
  "Turks and Caicos Islands": "Turks and Caicos",
  Taiwan: "台灣",
  "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
  "Pitcairn Islands": "Pitcairn Islands",
  "French Polynesia": "Polynésie française",
  "French Southern and Antarctic Lands":
    "Terres australes et antarctiques françaises",
  Seychelles: "Seychelles",
  Kiribati: "Kiribati",
  "Marshall Islands": "Marshall Islands",
  "Trinidad and Tobago": "Trinidad and Tobago",
  Grenada: "Grenada",
  "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
  Barbados: "Barbados",
  "Saint Lucia": "Saint Lucia",
  Dominica: "Dominica",
  "United States Minor Outlying Islands":
    "United States Minor Outlying Islands",
  Montserrat: "Montserrat",
  "Antigua and Barbuda": "Antigua and Barbuda",
  "Saint Kitts and Nevis": "Saint Kitts and Nevis",
  "United States Virgin Islands": "United States Virgin Islands",
  "Saint Barthelemy": "Saint Barthélemy",
  "Puerto Rico": "Puerto Rico",
  Anguilla: "Anguilla",
  "British Virgin Islands": "British Virgin Islands",
  Jamaica: "Jamaica",
  "Cayman Islands": "Cayman Islands",
  Bermuda: "Bermuda",
  "Heard Island and McDonald Islands": "Heard and McDonald Islands",
  "Saint Helena": "Saint Helena",
  Mauritius: "Mauritius",
  Comoros: "Comoros",
  "São Tomé and Principe": "São Tomé and Príncipe",
  "Cabo Verde": "Cabo Verde",
  Jersey: "Jersey",
  Guernsey: "Guernsey",
  "Isle of Man": "Isle of Man",
  Aland: "Åland Islands",
  "Faroe Islands": "Faroe Islands",
  "Indian Ocean Territories": "Indian Ocean Territories",
  "British Indian Ocean Territory": "British Indian Ocean Territory",
  "Norfolk Island": "Norfolk Island",
  "Cook Islands": "Cook Islands",
  "Wallis and Futuna": "Wallis and Futuna",
  Tuvalu: "Tuvalu",
  "Federated States of Micronesia": "Federated States of Micronesia",
  "South Georgia and the Islands":
    "South Georgia and the South Sandwich Islands",
  "Falkland Islands": "Falkland Islands",
  Niue: "Niue",
  "American Samoa": "American Samoa",
  Guam: "Guam",
  "Northern Mariana Islands": "Northern Mariana Islands",
  "Coral Sea Islands": "Coral Sea Islands",
  "Spratly Islands": "Spratly Islands",
  "Clipperton Island": "Clipperton Island",
  "Macao S.A.R": "澳门",
  "Ashmore and Cartier Islands": "Ashmore and Cartier Islands",
  "Bajo Nuevo Bank (Petrel Is.)": "Bajo Nuevo Bank",
  "Serranilla Bank": "Serranilla Bank",
  "Scarborough Reef": "Scarborough Reef",
  "Saint Martin": "Saint Martin",
  "Sint Maarten": "Sint Maarten",
  "US Naval Base Guantanamo Bay": "Guantanamo Bay",
  "Brazilian Island": "Brazilian Island",
  "Northern Cyprus": "Northern Cyprus",
  "Cyprus No Mans Area": "Cyprus No Mans Area",
};
